\documentclass{scrartcl}
\usepackage{microtype}
\usepackage{todonotes}
\usepackage{siunitx}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{fontspec}
\usepackage{hyperref}
\setmainfont{Palatino Linotype}

\begin{document}
\listoftodos
\section{Methodik}
\subsection{Clustering}
Hier wird partitionierendes Clustering betrieben. 

\missingfigure{Make a sketch of the structure of a trebuchet.}



\end{document}